export const CONSULTA_DATA_SUCCESS = 'CONSULTA_DATA_SUCCESS';
export const CONSULTA_DATA_ERROR = 'CONSULTA_DATA_ERROR';

export const CONSULTA_DATAMY_SUCCESS = 'CONSULTA_DATAMY_SUCCESS';
export const CONSULTA_DATAMY_ERROR = 'CONSULTA_DATAMY_ERROR';
